# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97549c5ad1a65cb31f65ae26112c566e6df73808f6b7eb4632cfbd9318fabddf36c34b98f4ccec6135e378455f335e92cc7bf1c7d64796d02c33581400c2fe79

test:
  secret_key_base: eb2f38560c6940923eb54c4f615468394cbeec7705cc69251b1d2be7fbc4c8e7e8cf204b0752313ba898d28e2761991652d1fc22cf58a65ac58e0dad69aaabb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
